### ISSUE TITLE
GPG: Verify libsodium and dnscrypt-proxy

### ISSUE THREAD

**Issue by theodorerambert** [simonclausen/dnscrypt-autoinstall#10]
The script should verify both libsodium-$LSODIUMVER.tar.gz and dnscrypt-proxy-$DNSCRYPTVER.tar.gz.

The sigs are available on both download pages.

gpg: key 1CDEA439: public key "Jedi/Sector One <j@pureftpd.org>"

**Comment by simonclausen** [comment]
I think we're there now and it's safe to close this. Alad, reopen if I'm mistaken.
