### ISSUE TITLE
Installation on Mint 17.3 fails on script command 'systemctl' 

### ISSUE THREAD

**Issue by anthony-ss** [simonclausen/dnscrypt-autoinstall#102]
Tried installing on Mint 17.3, which failed. Script needs 'sysctl' command not 'systemctl' at Lines 160 & 483, possibly others.

**Comment by AladW** [comment]
I have no idea what sysctl is and how it's supposed to replace systemctl, which is part of systemd.

https://www.freedesktop.org/software/systemd/man/systemctl.html

Either way, Mint 17.3 seems based on Ubuntu 14.04, so as the readme indicates the legacy branch is what you're looking for.

https://github.com/simonclausen/dnscrypt-autoinstall/blob/legacy/dnscrypt-autoinstall.sh
