### ISSUE TITLE
forcedel not working / script still complaining that dnscrypt is installed

### ISSUE THREAD

**Issue by shaoiken** [simonclausen/dnscrypt-autoinstall#105]
When trying to reinstall dnscrypt-autoinstall after an uninstall I get the error code: 
```
Error!

It seems like DNSCrypt is already installed but
not configured by this script.

Remove DNSCrypt and it's configuration completely
from the system and run this script again.

To uninstall DNSCrypt, try running this script
again with the 'forcedel' argument. For example:
./dnscrypt-autoinstall forcedel
```
So I run "sudo ./dnscrypt-autoinstall forcedel" which gives me:
```
chattr 1.43.4 (31-Jan-2017)
Flags von /etc/resolv.conf wie folgt gesetzt: --------------e----
etc/resolv.conf
Failed to stop dnscrypt-autoinstall.service: Unit dnscrypt-autoinstall.service not loaded.
Failed to disable unit: Unit file dnscrypt-autoinstall.service does not exist.
```
But after that dnscrypt-autoinstall still fails with the first error message. I'm on debian sid with all upgrades available. The dnscrypt packages from debian itself are not installed. I also tried to delete the files mentioned here [Issue #34 ](https://github.com/simonclausen/dnscrypt-autoinstall/issues/34) manually with the same result.

**Comment by darkerego** [comment]
Weird.... 

> The 'e' attribute indicates that the file is using extents for mapping 
> the blocks on disk.  It may not be removed using chattr(1).[ https://unix.stackexchange.com/questions/32256/whats-the-meaning-of-output-of-lsattr ](url)

**Comment by shaoiken** [comment]
Yeah that's weird, the file is on ext4 which supports the attribute and it is the auto-generated one by NetworkManager, the file /etc/resolv.conf has the following content:

```
# Generated by NetworkManager
nameserver 192.168.0.1
```

NetworkManager got an update not too long ago on debian sid, should I just try to remove the e attribute and try again?

**Comment by shaoiken** [comment]
Ok, I'm an idiot. I had a custom dnscrypt-proxy.conf residing in /etc/ which I forgot about, which was found by whereis and set get_location dnscrypt-proxy to be 1. Sorry for the inconvenience ...
