### ISSUE TITLE
gpg keys

### ISSUE THREAD

**Issue by RodRojas** [simonclausen/dnscrypt-autoinstall#107]
there is an gpg error in the installation of the legacy branch:

gpgkeys: key 54A2B8892CC3D6A597B92B6C210627AABA709FE1 can't be retrieved
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
Error importing key 54A2B8892CC3D6A597B92B6C210627AABA709FE1

PS: by the way, thank you so much for this project

**Comment by sambowne** [comment]
You can comment out the gpg signature verification lines to make it install; insecure but it works :)
Details here:

https://samsclass.info/120/proj/40-p2x-dnscrypt.htm

**Comment by simonclausen** [comment]
Archiving repo, see last comment in #108
