### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by heyhowareya11** [simonclausen/dnscrypt-autoinstall#34]
./dnscrypt-autoinstall.sh:
(errors)
mkdir: cannot create directory ‘./dnscrypt-autoinstall’: Permission denied
./dnscrypt-autoinstall.sh: line 224: pushd: ./dnscrypt-autoinstall: No such file or directory
Importing key with ID: 1CDEA439
gpg: requesting key 1CDEA439 from hkp server keys.gnupg.net
gpg: key 1CDEA439: "Jedi/Sector One <j@pureftpd.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   398    0   398    0     0   1062      0 --:--:-- --:--:-- --:--:--  1064
Warning: Failed to create the file libsodium-1.0.0.tar.gz: Permission denied
  1 1502k    1 16384    0     0  19734      0  0:01:17 --:--:--  0:01:17 19734
curl: (23) Failed writing body (0 != 16384)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file libsodium-1.0.0.tar.gz.sig: Permission 
Warning: denied
100    72  100    72    0     0     68      0  0:00:01  0:00:01 --:--:--    68
curl: (23) Failed writing body (0 != 72)
Verifying signature of: libsodium-1.0.0.tar.gz
gpg: can't open `libsodium-1.0.0.tar.gz.sig'
gpg: verify signatures failed: file open error
Error verifying signature

Tried running the script inside a root shell (sudo -i), this gives:
You should not run this script directly as root.

**Comment by AladW** [comment]
Any follow up on this? From what path did you run the script exactly?

**Comment by simonclausen** [comment]
Heyhowareya, I'm closing this. If you are still having issues, please get back on this.
