### ISSUE TITLE
GPG Request Failed

### ISSUE THREAD

**Issue by caisar** [simonclausen/dnscrypt-autoinstall#39]
The problem came when DNScrypt unable to resolve my DNS request few days ago, so I uninstall it. Now when I try to install it in my ubuntu 14.04 laptops again and always had fail GPG request. 

![screenshot from 2015-01-16 06 51 35](https://cloud.githubusercontent.com/assets/5735742/5769308/2678af50-9d4c-11e4-858d-2be1ea25621a.png)

**Comment by AladW** [comment]
Check your firewall settings

http://unix.stackexchange.com/questions/75892/keyserver-timed-out-when-trying-to-add-a-gpg-public-key

**Comment by simonclausen** [comment]
@caisar, do you still have this issue? Please get back to us :)

**Comment by caisar** [comment]
No. It works fine now. The problem is in my firewall setting.

**Comment by simonclausen** [comment]
Good to hear. Thanks for getting back!
