### ISSUE TITLE
gpg: Can't check signature: public key not found

### ISSUE THREAD

**Issue by wayne13** [simonclausen/dnscrypt-autoinstall#41]
I love this script!
It is failing to verify libsodium-1.0.1.tar.gz.sig :(

I vaguely remember having and overcoming this issue about 6 months ago.  Not having as much luck this morning.

elementary os luna(ubuntu 12.04)

This is a gpg issue with Frank DENIS (Jedi/Sector One).  Looks like it was solved a while back by pulling from github but thats not working any longer.  Any pointers greatly appreciated.

Thank you

**Comment by jedisct1** [comment]
Maybe because I recently switched to a new PGP key. Everything has been resigned with the new key, including dnscrypt and sodium.

New key is here: http://pgp.mit.edu/pks/lookup?op=vindex&search=0x210627AABA709FE1

**Comment by ciuncan** [comment]
@jedisct1 I can confirm your your solution, changing `1CDEA439` into `BA709FE1` in 'dnscrypt-autoinstall.sh' worked. 
Can you update your repository as well?

**Comment by simonclausen** [comment]
Thanks for the headsup!

**Comment by wayne13** [comment]
Thank you very much :+1:

**Comment by ciuncan** [comment]
You're very velcome. :)
