### ISSUE TITLE
Minor Issue with LSODIUMURL

### ISSUE THREAD

**Issue by FlashLite** [simonclausen/dnscrypt-autoinstall#42]
LSODIUMVER=1.0.2
LSODIUMURL="https://github.com/jedisct1/libsodium/releases/download/1.0.1" -> ~/1.0.2

**Comment by simonclausen** [comment]
Was a bit too quick about that last commit. I apologize - thank you for letting me know :)

**Comment by FlashLite** [comment]
No problem.  And thank you very much for this project.
