### ISSUE TITLE
Enhancement - Setting up DNS

### ISSUE THREAD

**Issue by ssoto2** [simonclausen/dnscrypt-autoinstall#46]
The method in the debian/ubuntu script is not best practice

The following would be recommended to be changed

		# Set up init script
		config_do
		
		# Set up resolv.conf to use dnscrypt
		sudo bash <<EOF
		mv /etc/resolv.conf /etc/resolv.conf-dnscryptbak
		echo "nameserver 127.0.0.1" > /etc/resolv.conf
		echo "nameserver 127.0.0.2" >> /etc/resolv.conf
		
		# Dirty but dependable
		chattr +i /etc/resolv.conf

Resolve.conf alert the following:
```
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
```

chattr as stated is a dirty solution. 

i would recommend reviewing https://raam.org/2009/configuring-static-dns-with-dhcp-on-debianubuntu/
where dhcpclient.conf is modified instead and then use "supersede"

ex) supersede domain-name-servers 8.8.8.8, 8.8.4.4;

also possible option is to append /etc/resolvconf/resolv.conf.d/tail which would append additions to resolv.conf

**Comment by ssoto2** [comment]
this references issue #15 which can be addressed better by performing a couple checks to find dhcpclient.conf and modifying..  If some part of the install flubs it could prevent internet access and seriously inconvenience a novice user not aware of how to correct the problem.

**Comment by simonclausen** [comment]
Thank you for the suggestion. Would this work in a OpenVZ container run by SolusVM or similar, which overwrites resolv.conf?

**Comment by AladW** [comment]
The problem is that this is specific to solutions that respect dhcpclient.conf. AFAIK, connman, network manager, etc. don't do this.
