### ISSUE TITLE
Enhancement Request - Logging 

### ISSUE THREAD

**Issue by ssoto2** [simonclausen/dnscrypt-autoinstall#47]
add the option of --logfile to the init scripts would be a nice default 

ex) --logfile=/var/logs/dnscrypt

**Comment by simonclausen** [comment]
Enabling logging would depend on setting up log rotation on the host system as well to avoid large logs. This seems like a lot of complexity to add for an optional feature.

I'm hesitant to include this.

**Comment by AladW** [comment]
I agree, logs are saved in /var/log/daemon.log or the systemd journal, e.g

journalctl -u dnscrypt-proxy.service
