### ISSUE TITLE
Libsodium never gets updated

### ISSUE THREAD

**Issue by lucaspetter** [simonclausen/dnscrypt-autoinstall#56]
The way the script currently works, there's no way for users to ever get updated versions of libsodium. This is because the script doesn't uninstall it and because it won't install a newer version if an older one is currently installed. For example:
1. User has never installed dnscrypt-proxy or libsodium before.
2. User runs dnscrypt-autoinstall.sh for the first time, installs `dnscrypt-proxy X.X.1` and `libsodium Y.Y.1`.
3. Newer versions of the software are released and dnscrypt-autoinstall.sh is updated to use these versions: `dnscrypt-proxy X.X.2` and `libsodium Y.Y.2`.
4. User wants to get the software updates, so gets the latest copy of dnscrypt-autoinstall.sh, runs it, and selects the option to uninstall. `dnscrypt-proxy X.X.1` is removed, but `libsodium Y.Y.1` remains installed because the script doesn't remove it.
5. User runs dnscrypt-autoinstall.sh again. Because the script detects that `libsodium Y.Y.1` is installed, it leaves it untouched, but continues installing the new `dnscrypt-proxy X.X.2`.
6. User now has `dnscrypt-proxy X.X.2` and `libsodium Y.Y.1`, even though `libsodium Y.Y.2` is available. There's no easy way for the user to get `libsodium Y.Y.2`.

This could be fixed by uninstalling libsodium when running the `config_del` uninstallation function, or by automatically uninstalling right before the script is about to install a newer version, or by asking the user if they want to uninstall the old version and install the newer one like in #32, or all of the above.

I wonder: why are we currently avoiding touching libsodium? Are we trying to avoid uninstalling it so we don't break other potentially-installed software that may be using it? I couldn't find any past discussion about this.

**Comment by lucaspetter** [comment]
According to the code, users running Fedora 19/20 may be an exception to this because they have `libsodium-devel`, which would get updated whenever the new version arrives in their repositories:
```
# Fedora 19/20 include libsodium
yum install -y libsodium-devel && LSODIUMINST=true
```

**Comment by simonclausen** [comment]
That's spot on. We are not touching libsodium, because we do not know if it is being used for anything else on the system. While libsodium is not as widely used as OpenSSL, imagine removing OpenSSL while removing i.e. Apache. We can't make the assumption that dnscrypt is the only user of libsodium :)

You are raising valid points though and this should probably be solved by 1) asking the user if they want to uninstall libsodium as a prompt when removing dnscrypt, 2) detect libsodium version at dnscrypt install and ask if they want to upgrade, or 3) both the previous options.

**Comment by AladW** [comment]
Fedora and OpenSUSE don't necessarily have the latest libsodium either. Perhaps we could query the user in using the latest upstream release locally, at least if this doesn't break packages depending on an older version.

**Comment by simonclausen** [comment]
Archiving repo, see last comment in #108
