### ISSUE TITLE
"Automated" mode

### ISSUE THREAD

**Issue by simonclausen** [simonclausen/dnscrypt-autoinstall#61]
Would it make sense to give users the ability to run the script with parameters instead of interacting with a GUI?

**Comment by lucaspetter** [comment]
How about both: run with parameters, but if no parameters are present then it uses the current UI mode.

**Comment by simonclausen** [comment]
Yeah, that sounds like a good way to do it

**Comment by RichardLaing** [comment]
Any update on that parameters mode?

**Comment by AladW** [comment]
Patches welcome.

**Comment by simonclausen** [comment]
Archiving repo, see last comment in #108
