### ISSUE TITLE
Not starting systemd service in Ubuntu 15.04

### ISSUE THREAD

**Issue by eksperimental** [simonclausen/dnscrypt-autoinstall#66]
dnscrypt-proxy.service has more than one ExecStart= setting, which is only allowed for Type=oneshot services. Refusing.

**Comment by eksperimental** [comment]
I think the ppa in ubuntu installed some files, and it broke the current installation
``
/lib/systemd/system/dnscrypt-proxy-resolvconf.service
/lib/systemd/system/dnscrypt-proxy.service
/lib/systemd/system/dnscrypt-proxy.socket
```
even after i removed the package, and also uninstalled dnscrypt-autoinstall, including with the "forcedel" option, I wasn't able to start the service, 

` sudo systemctl start dnscrypt-proxy.service`
or
` sudo systemctl enable dnscrypt-proxy.service`

would give 
> systemd[1]: dnscrypt-proxy.service has more than one ExecStart= setting, which is only allowed for Type=oneshot services. Refusing.

Only when I removed these files in /lib/ and resintalled dnscrypt with this script, i manged to get it running

Maybe we should remove these files, when we execute the "forcedel"  option
` sudo rm /lib/systemd/system/dnscrypt-proxy*`

**Comment by AladW** [comment]
Removing system services in /lib breaks distribution packages such as those provided by Arch Linux. Have you filed a bug on the PPA page?

**Comment by eksperimental** [comment]
you are right.
Nope i haven't.
That PPA corrupted my whole installation, didn't want to deal with it any more.. sorry
