### ISSUE TITLE
Remove systemd scripts?

### ISSUE THREAD

**Issue by AnAkkk** [simonclausen/dnscrypt-autoinstall#68]
On Arch, the dnscrypt-proxy is now compiled with systemd support, which means it now provide its own systemd scripts, which have the same name as dnscrypt-autoinstall one.

Since systemd support is available in dnscrypt-proxy, shouldn't the scripts from dnscrypt-autoinstall be removed?

**Comment by AladW** [comment]
See my reply on the AUR page:

> Well, services in /etc override those in /usr/lib (see systemd.unit, Unit Load Path). So it should still work (the socket would call the service in /etc).

> Either way, I'll update this in line with the official package. Thanks for reporting.

**Comment by AnAkIn1** [comment]
Right, well maybe this can be closed then, or I can leave it opened if you want to integrate dnscrypt-autoinstall more closely with the official dnscrypt-proxy (maybe make it edit the systemd service directly instead of creating a conf file?)

**Comment by AladW** [comment]
Considering upstream now defaults to a well-commented service (https://github.com/jedisct1/dnscrypt-proxy/commit/45884045caf88bc136e12c4ad0f9e57334feec61), changing the resolver in Arch should only be a matter of `systemctl edit --full dnscrypt-proxy.service`. As such, I'll remove the scripts here and the AUR package.
