### ISSUE TITLE
Install dependencies

### ISSUE THREAD

**Issue by simonclausen** [simonclausen/dnscrypt-autoinstall#69]
Debian script: needs installation of curl/build-essential

**Comment by simonclausen** [comment]
+ sudo

**Comment by williclarkam** [comment]
Sir, I think it's good idea to add to "Installation" section, that Debian users should install sudo before beginning to install.
sudo isn't pre-installed on Debian (at least on Debian 8 [jessie])
Debian users can install sudo easily with the command below
`apt install sudo` 
if they don't have root access, they can easily change to root 
`su - root`
and then easily install sudo.
Hope this helps.

**Comment by AladW** [comment]
The next version of dnscrypt-autoinstall will not rely on sudo, using a dedicated build user to download and build the sources instead. See #64
