### ISSUE TITLE
Verifiying signature error

### ISSUE THREAD

**Issue by meeeo** [simonclausen/dnscrypt-autoinstall#70]
![scrnshot](https://cloud.githubusercontent.com/assets/5188710/10991065/ffbd2c5c-8494-11e5-9a05-b92fa0980af5.png)

I run this script on my raspberry pi, keep getting this gpgkey verification error again  and again, so is there something wrong?

**Comment by meeeo** [comment]
This is not a bug, because I'm locate in China, as you know, dnscrypt.org got blocked, finally I installed it manually on my raspberry pi, thanks.

**Comment by darkerego** [comment]
Actually, this happens to me almost everytime I use the script. However, it always succeeds if I run it again. Odd.

**Comment by squirrelboot** [comment]
Hello,

I have just recently installed Debian 8.3 x64 Cinnamon, in VM Virtualbox. Things seem pretty normal, all updates, etc.

One of the first things I usually do when setting up a system is DNSCrypt, and this script. Never had issues with it, and it's the best! Thanks by the way! But, this one time, it absolutely refuses to install. 

http://pastebin.com/i6ch2n35

What's going on?

**Comment by squirrelboot** [comment]
Ok this is lame.. after I stopped to take the time to google this page, log in, write that up, go and paste on pastebin, and come back and post. I go back and try the script and it works. What causes this behavior? To me it seems so bizarre. :game_die:

**Comment by darkerego** [comment]
I can't read your paste, looks like it was removed. Did you also get the signature error, and did it work the second time? If that's the case, although I don't think it has anything to do with this script per say, I do think it's weird and should be looked into.

**Comment by AladW** [comment]
I'm guessing this is due to dnscrypt.org not responding, and thus the version field not being filled in.

**Comment by AladW** [comment]
via https://github.com/simonclausen/dnscrypt-autoinstall/commit/84660d27e337c10185514470d803e1b060dd7158#diff-862fb7e008abfd4c8c5d0443c6725390R54
