### ISSUE TITLE
AutoStart issue

### ISSUE THREAD

**Issue by dharm910** [simonclausen/dnscrypt-autoinstall#72]
The script does not work with reboot of Linux . I have to always run it manually after the restart.
This is the log which I gets once I run the script manually.
Starting dnscrypt-proxy
chattr: Operation not supported while reading flags on /etc/resolv.conf
chattr: Operation not supported while reading flags on /etc/resolv.conf
Reconfiguration done. Quitting

**Comment by AladW** [comment]
What distribution?

**Comment by dharm910** [comment]
I am using Linux Mint 17.2 Rafaela however , today after reinstallation it is now auto starting after reboot not sure what it was not working before.
Did you tried uninstallation of the script ?

**Comment by AladW** [comment]
Post ```ls -l /etc/resolv.conf```

**Comment by simonclausen** [comment]
@dharm910, please get back with more info on this, if still relevant.

Keeping open because possible relation to #71

**Comment by williclarkam** [comment]
I think this issue doesn't happen on Debian 8 (Jessie) because every time that I reboot the server, I issue the command `sudo tail -n 200 /var/log/syslog` and the output shows that dnscrypt-proxy has started. but still I maybe wrong, still new to Linux ;)

**Comment by dharm910** [comment]
I am not facing any issue now as after a reinstallation it's working fine now

**Comment by AladW** [comment]
Without more information, I'm going to classify this as a dupe of #79
