### ISSUE TITLE
Cannot create directory (Debian testing)

### ISSUE THREAD

**Issue by gerroon** [simonclausen/dnscrypt-autoinstall#73]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 54A2 B889 2CC3 D6A5 97B9  2B6C 2106 27AA BA70 9FE1
     Subkey fingerprint: 0C79 83A8 FD9A 104C 6231  72CB 62F2 5B59 2B6F 76DA
/xxxxx/dnscrypt-autoinstall/libsodium-1.0.8 /xxxxx/dnscrypt-autoinstall /xxxxx
checking build system type... mkdir: cannot create directory './dnscrypt-autoinstall/cg9021-426': No such file or directory
mkdir: cannot create directory './dnscrypt-autoinstall/cg-9021': No such file or directory
config.guess: cannot create a temporary directory in ./dnscrypt-autoinstall
configure: error: cannot guess build type; you must specify one
/xxxxx/dnscrypt-autoinstall /xxxxx
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

**Comment by gerroon** [comment]
Nevermind.

I had to run "sudo -u user" as root to make it work. Standard sudo does not work, at least it did not work for me.

**Comment by AladW** [comment]
As what user did you initially run the script, and in what directory?

**Comment by gerroon** [comment]
I initially run as my normal user`s sudo but that did not work if I remember right.

**Comment by AladW** [comment]
Yeah, the script itself calls sudo when it needs to due to 10#issuecomment-50569513. Running it directly with root privileges is a bad idea, not sure how that could even happen.

**Comment by simonclausen** [comment]
@AladW, any need to do anything further with this in your opinion?

**Comment by AladW** [comment]
Not sure what else there is to do here without further information, so this can be closed. Similar issues should be covered when #64 is implemented.
