### ISSUE TITLE
Ubuntu 15.10 X64 /etc/resolv.conf issue

### ISSUE THREAD

**Issue by williclarkam** [simonclausen/dnscrypt-autoinstall#79]
Hi,

I have always installed this script on Debian 8 Jessie, and every time after the installation has finished I checked `/etc/resolv.conf` entries, and there was some warning below the screen "Permission Denied" , so I think this script makes `/etc/resolv.conf` file "immutable" so it doesn't get after each reboot written, BUT now I wanted to test Ubuntu 15.10 and this file isn't "immutable" , and I can edit it, so I think, that this may bring issues after the server reboots. I think it would be better, if we make this file immutable? 
`sudo chattr +i /etc/resolv.conf`
UPDATE_1: So I wanted to configure the servers and these are the 2 errors:
```
chattr: Operation not supported while reading flags on /etc/resolv.conf
chattr: Operation not supported while reading flags on /etc/resolv.conf
```
so I assume you have added this command  to the script but it doesn't work somehow!

**Comment by AladW** [comment]
`stat /etc/resolv.conf`

**Comment by williclarkam** [comment]
I have ran the command you mentioned, and the first line is:
`File: ‘/etc/resolv.conf’ -> ‘../run/resolvconf/resolv.conf’`

**Comment by AladW** [comment]
The problem is we're writing the local DNS address to the _target_ of the symbolic link, but try to run chattr on the symbolic link itself, which fails. The script should move the link to a backup location, rather than copy and write to it.

**Comment by simonclausen** [comment]
Reference note: this is probably the same issue as #71, possibly #72.

**Comment by AladW** [comment]
Using realpath -e /etc/resolv.conf should fix this. Please test the script in the fakeroot branch and continue discussion in #64
