### ISSUE TITLE
CentOS/Redhat script broken...doesn't appear to set a valid/working server- Add manual server entry choice!

### ISSUE THREAD

**Issue by NoX1De** [simonclausen/dnscrypt-autoinstall#80]
When trying to select a server...tried a few different choices and when the script finishes dnscrypt is not working...

[ERROR] No resolver named [OpenDNS] found in the [/usr/local/share/dnscrypt-proxy/dnscrypt-resolvers.csv] list

Appears to maybe be a problem with the format/mapping of the names in the .csv?
Seems to be a problem with some of the OpenNIC servers as well.

Better yet, how about we add the choice to manually specify a dnscrypt supported server of our choosing and type in the IP manually during the script execution if we so choose??

**Comment by williclarkam** [comment]
On Debian Based systems, you can edit the IPs and Keys under /etc/init.d/dnscrypt-proxy with your favorite editor (nano/vi/vim...), I think in CentOS/RHEL should be similar, I know they don't use sysV/upstart but under some systemd directory you can find the dnscrypt-proxy file to edit it.

**Comment by NoX1De** [comment]
On raspbian I found it under /usr/local/share/dnscrypt-proxy either way I've found that the file just points to the dnscrypt-resolvers.csv....I have no idea why they are doing it this way using this .csv file it just seems really ridiculous to me...I don't know if or how often the csv is pulled down but if it's just a static file that gets pulled down once at installation it seems even more ridiculous...I suppose I could find out if dnscrypt-proxy checks for a new csv somewhere online every so often and disable that and then create my own csv with the servers of my choice and create the names I want for them to use when initializing dnscrypt-proxy on boot...ugh...wtf.

**Comment by NoX1De** [comment]
Or...maybe /usr/local/share/dnscrypt-proxy will accept the IP addresses of the servers of my choice rather than it pointing to the .csv? I dunno since there is no documentation I've come across.  I did see I can pass a server directly via the command to initialize dnscrypt-proxy...anyhow I should get it sorted out.

**Comment by simonclausen** [comment]
@NoX1De, the script does not use the csv, but provides dnscrypt-proxy directly with hardcoded details of the servers: using the csv is a possible feature improvement (handled in #62). I have split out "add custom server" in #84. As @williclarkam mentioned you can edit the init files to your liking as a workaround for now.

That leaves the error you posted: where is that output from? I wonder why dnscrypt-proxy tries to use the cvs. Did you run it directly?

**Comment by AladW** [comment]
Due to inactivity, closing as duplicate of #62
