### ISSUE TITLE
$LSODIUMVER isnt the newest version

### ISSUE THREAD

**Issue by fred0r** [simonclausen/dnscrypt-autoinstall#82]
I'm using this on Debian Jessie and the Script only downloads the 1.0.9 of libsodium.
But theres are newer Version on the DL-Site:
https://download.libsodium.org/libsodium/releases/libsodium-1.0.10.tar.gz

**Comment by simonclausen** [comment]
Hi @fred0r - yes, it does indeed seem like the version parsing is broken: I can confirm getting "1.0.9" on Debian.

**Comment by AladW** [comment]
This is because the next version is 1.0.**1**0, which is seen as "older" than 1.0.**9**. `sort -V` should fix this.
The following works:
```
curl -sSL https://download.libsodium.org/libsodium/releases | awk -F '(</?a( href=")?|">|-)' '$2 ~ /libsodium/ && $3 ~ /[0-9]$/ {print $3 | "sort -uV"}' | tail -1
```

**Comment by AladW** [comment]
The next version of the script will use this filter:
```
awk -F '</?a( href=\".+\">)?' -v name="^$1-[0-9.]+\.tar\.gz$" '$2 ~ name {print $2}'
```
together with sort -V. See #64

**Comment by fred0r** [comment]
thx
