### ISSUE TITLE
It looks like there is already a DNS server or forwarder installed and listening on 127.0.0.1.

### ISSUE THREAD

**Issue by meaverick** [simonclausen/dnscrypt-autoinstall#83]
> pi@Pi3:~ $ uname -a
Linux Pi3 4.4.9-v7+ #884 SMP Fri May 6 17:28:59 BST 2016 armv7l GNU/Linux
pi@Pi3:~ $ ./dnscrypt-autoinstall.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   185  100   185    0     0     88      0  0:00:02  0:00:02 --:--:--    88
100  8810    0  8810    0     0   3560      0 --:--:--  0:00:02 --:--:-- 4301k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   185  100   185    0     0     89      0  0:00:02  0:00:02 --:--:--    89
100  3815    0  3815    0     0    792      0 --:--:--  0:00:04 --:--:--  2768

Error!

It looks like there is already a DNS server
or forwarder installed and listening on 127.0.0.1.

To use DNSCypt, you need to either uninstall it
or make it listen on another IP than 127.0.0.1.

To uninstall DNSCrypt, try running this script
again with the 'forcedel' argument. For example:
    ./dnscrypt-autoinstall.sh 

> forcedel

>

**Comment by simonclausen** [comment]
Reopen if this is still an issue with a description of what's wrong
