### ISSUE TITLE
Add custom server(s)

### ISSUE THREAD

**Issue by simonclausen** [simonclausen/dnscrypt-autoinstall#84]
As mentioned in #80

**Comment by AladW** [comment]
The script helps in selecting from a list of existing providers; if you don't want to use any of these, it's a small step to define your own server(s) in the dnscrypt service file. As such, I'm not sure on the benefit of supporting this.

**Comment by simonclausen** [comment]
You're probably right. The biggest benefit from autoinstall is that - installation management. Maybe it would be enough to do a short guide in the readme on how to put in a custom config. What do you think?

**Comment by AladW** [comment]
Yep, I think that's a good compromise.

**Comment by simonclausen** [comment]
Archiving repo, see last comment in #108
