### ISSUE TITLE
CentOS 7 ncat

### ISSUE THREAD

**Issue by l0rda** [simonclausen/dnscrypt-autoinstall#85]
Hello,

nc in CentOS 7 was replaced by nmap-ncat, so they have different params(e.g. -z skipped) and autoinstall script does not work on CentOS 7. BTW, script still works if /usr/bin/nc is not found.

**Comment by AladW** [comment]
Hi, please provide a pull request updating the flags in dnscrypt-autoinstall-redhat.sh. Thanks

**Comment by AladW** [comment]
via https://github.com/simonclausen/dnscrypt-autoinstall/commit/a73f38fd7e8cedfcf168800d6a327116d1432169
