### ISSUE TITLE
Configuring another server wipes the init.d script

### ISSUE THREAD

**Issue by gerroon** [simonclausen/dnscrypt-autoinstall#90]
I get a lot of time outs and the errors below

As you see at the bottom  "/etc/init.d/dnscrypt-proxy: line 1: 404:: command not found", basically it replaces the content of the script with 404. Thank goodness I had a copy of the original script. I tried this multiple times and it always replaced the content with that bogus line.

I am using Debian Testing 64bit.

Welcome to dnscrypt-autoinstall script.

It seems like DNSCrypt was installed and configured by this script.

What would you like to do?

1) Configure another DNSCrypt service
2) Uninstall DNSCrypt and remove the auto-startup config
3) Exit

Select an option [1-3]: 1

Which DNSCrypt service would you like to use?

1) DNSCrypt.eu (Europe - no logs, DNSSEC)
2) OpenDNS (Anycast)
3) CloudNS (Australia - no logs, DNSSEC)
4) OpenNIC (Japan - no logs)
5) OpenNIC (Europe - no logs)
6) Soltysiak.com (Europe - no logs, DNSSEC)

Select an option [1-6]: 5
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:18 --:--:--     0
100    15    0    15    0     0      0      0 --:--:--  0:00:19 --:--:--    15
Stopping dnscrypt-proxy
insserv: script zfs: service zfs already provided!
insserv: warning: script 'dnscrypt-proxy' missing LSB tags and overrides
insserv: script zfs: service zfs already provided!
/etc/init.d/dnscrypt-proxy: line 1: 404:: command not found
Reconfig done. Quitting.

**Comment by AladW** [comment]
If the URL for the init script is wrong, curl will write 404 Not Found to the target file. To avoid issues like this, the script in the master branch uses a single service, instead of a different one for each dnscrypt provider. As you're on Debian Testing, I'm unsure why you're going with the old version.

**Comment by gerroon** [comment]
I am not sure about te version. I just downloaded the zip from the git repo, or whatever the github.provided me on the entry page

**Comment by AladW** [comment]
Odd. Try the following link:

https://raw.githubusercontent.com/simonclausen/dnscrypt-autoinstall/master/dnscrypt-autoinstall

**Comment by simonclausen** [comment]
This is directly related to us not having managed how old scripts deal with radical changes in functionality in new versions: the old version(s) of the script looking for something that is not longer in the master.

On one hand we could have had some update check in the old scripts. On the other we could have left the files needed by old scripts in master.

We probably have a bunch of old versions out there. We could add version numbers and update check from now onward. But then again, that may be overkill. If people have issues, they will probably come here and find the new version in the process.

Maybe we should post a note about it in the readme?

**Comment by AladW** [comment]
Well, we don't use the sysvinit scripts in the master branch yet so might as well restore the old files there for backwards compability. Until then, I've updated the README and paths in the legacy branch to actually point there, rather than the master branch.

**Comment by AladW** [comment]
Closing due to lack of response from OP
