### ISSUE TITLE
systemctl: command not found

### ISSUE THREAD

**Issue by pimseb** [simonclausen/dnscrypt-autoinstall#93]
Hello,

I've been using dnscrypt for months but today the dns service stopped working.
So I decided to download your script again and reinstall it.
I'm running linux mint 17.1 64bits
With the previous of your script, everything went ok but with the last one the install stops with this error : 
./dnscrypt-autoinstall: line 483: systemctl: command not found
Can you help me or provide me the old version of your script ?
Thank you

**Comment by AladW** [comment]
https://github.com/simonclausen/dnscrypt-autoinstall/blob/master/README.md
