### ISSUE TITLE
Secondary dns server

### ISSUE THREAD

**Issue by iyx** [simonclausen/dnscrypt-autoinstall#98]
Hi, how to set secondary dns server?

Because of instability some fallback option is necessary.

**Comment by elgab** [comment]
Choosing dnscrypt.eu will just work, you should see both resolvers exposed with this: https://www.grc.com/dns/dns.htm

**Comment by iyx** [comment]
Alright I will test that.

Btw, installer fails to get resolvers list:
``0curl: (6) Could not resolve host: download.dnscrypt.org
Retrieving resolvers failed. Falling back to installed version.``

**Comment by AladW** [comment]
Yes, the dnscrypt.org site is highly unreliable. Again, no real
alternatives here due to github not containing any GPG signatures.

**Comment by simonclausen** [comment]
@AladW, there seems to be a minisig included consistently with the latest releases on Github. Would it be too much to build and use this for verification? Would it even make sense as that then presents the problem of how the minisig source is verified?

**Comment by AladW** [comment]
Right, the minisign source tarball is signed by another minisig file...

**Comment by simonclausen** [comment]
Original question was answered and the question on where to get files will probably be handled in #108 in relation to the new status of dnscrypt-proxy.
