### ISSUE TITLE
How to enhance performance with caching?

### ISSUE THREAD

**Issue by hellyberry** [simonclausen/dnscrypt-autoinstall#99]
How can caching be enabled or implemented? Currently it resolves each DNS request again. That could be 10 or x00 times the same DNS lookup on a single webpage.
Can dnsmasq be configured to support this?

It would enhance the performance and responsiveness especially for (AJAX-) websites or webapps and where low latency is required.

**Comment by jedisct1** [comment]
No need for dnsmasq, dnscrypt-proxy already supports caching.
This just has to be enabled in the config file:
```
## Cache DNS responses to avoid outgoing traffic when the same queries
## are repeated multiple times in a row.

LocalCache on
```

**Comment by simonclausen** [comment]
Would we want to default to enable caching in dnscrypt-proxy by default? Or should that be handled by the user outside of the scope of this script, as it would with DNS cache on linux in general?

@jedisct1, thanks for taking the time to reply on this.

**Comment by jedisct1** [comment]
Yes, yes, yes, I would say yes, absolutely yes.

This will ensure that users painlessly get a minimal caching layer, which is sadly not so common on Linux platforms.

And a much more advanced caching server can still be used in addition to it.

**Comment by AladW** [comment]
Looks like this is part of the default config which we don't change: https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-proxy.conf#L75

**Comment by jedisct1** [comment]
Mmmmm... Does dnscrypt-autoinstall actually use the config file? It doesn't seem to.

**Comment by AladW** [comment]
My bad, I missed the https://github.com/jedisct1/dnscrypt-proxy/blob/master/man/dnscrypt-proxy.8.markdown#common-usage-example-without-a-configuration-file section.

**Comment by hellyberry** [comment]
Great, works fine, thank you. Problem solved. :)

**Comment by hellyberry** [comment]
Great, works fine, thank you. Problem solved. :)

**Comment by shaoiken** [comment]
hellyberry could you describe how you activated the "LocalCache on" flag or made dnscrypt-autoinstall use the config file? 
The missing caching is totally killing my steam performance and I don't want to setup dnscrypt manually or with another dns caching solution.

**Comment by darkerego** [comment]
@shaoiken  If you are on a Debian type system, you can try something like this: 
`sudo bash -c 'echo "LocalCache on" >>/etc/systemd/system/dnscrypt-autoinstall.conf'`
